### ISSUE TITLE
PRs to Roam Depot

### ISSUE THREAD

**Issue by mdroidian** [RoamJS/query-builder#135]
@dvargas92495 Is there a way to merge to main without triggering a PR to Roam Depot.

Use Case:
- create a quick bug fix for immediate use via http://samepage.network/releases
- create a permanent fix later that will sent to Roam Depot

I was under the impression that updating the version triggered the PR, but this latest commit looks like it triggered it as well.
https://github.com/RoamJS/query-builder/pull/134

**Comment by dvargas92495** [comment]
You could change the `main.yaml` so that it only triggers on changes to package.json (releases)

**Comment by mdroidian** [comment]
note to self, branches are published on /releases as well
