### ISSUE TITLE
Sort DNP chronologically

### ISSUE THREAD

**Issue by mdroidian** [RoamJS/query-builder#151]
when column returns DNP (eg `has title` `{date}`) the option to sort chronologically should be there.

Some possible options:
 - right click, `Sort Chronologically`
 - implement [native query sorting](https://github.com/RoamJS/query-builder/blob/main/docs/roam-queries.md#sorting) somehow in the UI

Originally surfaced by Ivo in [slack](https://roamresearch.slack.com/archives/C016N2B66JU/p1693912478632889)

**Comment by dvargas92495** [comment]
this should already be supported, and if not, should be viewed as a bug

**Comment by mdroidian** [comment]
Added to slack thread last week.

It seems to be working on my end:

https://github.com/RoamJS/query-builder/assets/3792666/6b8cdcec-df3d-4cc6-8222-3bcb7466d6a5

Will close in a week or so if no response.
