### ISSUE TITLE
Is there a way to make a "with text" condition be case insensitive?

### ISSUE THREAD

**Issue by power833** [RoamJS/query-builder#233]
Currently, "with text" conditions seem to be case-sensitive. Is there a way to change this behavior to make them case insensitive?

Thanks!

**Comment by mdroidian** [comment]
Ah, not yet. 😞 But it is on the list! 👍
This ticket https://github.com/RoamJS/query-builder/issues/37 would allow regular expressions which can be case insensitive.

I'm going to go ahead and close as a duplicate of https://github.com/RoamJS/query-builder/issues/37
