### ISSUE TITLE
Discourse Graph Malfunctions

### ISSUE THREAD

**Issue by DelmarHuang** [RoamJS/query-builder#277]
Hi @mdroidian @dvargas92495, thanks for this amazing extension first of all!

I tried the Discourse Graph feature today but I think it malfunctions. After refreshing the page, the Overlay after the Evidence disappeared and the Claim cannot query all the Evidence as shown in the attached pictures.

- No Overlay after Evidence

<img width="544" alt="image" src="https://github.com/user-attachments/assets/22a3966b-4599-480f-9aa1-1bb6ade7e632">

- Failed query for Claim

<img width="585" alt="image" src="https://github.com/user-attachments/assets/5fc76676-a4af-4934-ae64-b05f56161b5f">

It shows loading all the time. And clicking on refresh overlay has no feedback.

**Comment by mdroidian** [comment]
**re: No Overlay after Evidence**

The default `Evidence ` that ships with Discourse Graphs actually requires a `Source`.
If you create the `Evidence` while in a `Source` page, it will automatically add the `Source` to the end of the `Evidence`.
To change this behavior, you can remove the ending ` - {Source}` from the format definition at `[[discourse-graph/nodes/Evidence]]`

![image](https://github.com/user-attachments/assets/76934930-8e0f-47ac-b5f3-3b3a8987c4fa)

**Comment by mdroidian** [comment]
**re: Failed query for Claim**

I've started a new issue for this one here: https://github.com/RoamJS/query-builder/issues/278
