### ISSUE TITLE
Embed Page displays two titles

### ISSUE THREAD

**Issue by mdroidian** [RoamJS/query-builder#45]
Seems like [Feb 7 roam API changes](https://roamresearch.com/#/app/developer-documentation/page/ym8aW5Cq8) makes `renderBlock` render the whole page

- [ ] remove this line
https://github.com/dvargas92495/roamjs-query-builder/blob/2f972dfcc0707cfef71d24b737f49852c06ee805/src/components/ResultsView.tsx#L136
- [ ] cleanup unused css
- [ ] make it look nice

**Comment by dvargas92495** [comment]
There's a couple more places we do this too that we'll want to clean up - I believe the Discourse Graph Relation Preview is one

**Comment by dvargas92495** [comment]
@mdroidian we're good to close this right?
